// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopmodelcredential"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopModelCredential is the model entity for the DesktopModelCredential schema.
type DesktopModelCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"device_id,omitempty"`
	// ConnectionGrantID holds the value of the "connection_grant_id" field.
	ConnectionGrantID string `json:"connection_grant_id,omitempty"`
	// SessionFamilyID holds the value of the "session_family_id" field.
	SessionFamilyID string `json:"session_family_id,omitempty"`
	// TokenVersion holds the value of the "token_version" field.
	TokenVersion int64 `json:"token_version,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// RevokeReason holds the value of the "revoke_reason" field.
	RevokeReason string `json:"revoke_reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DesktopModelCredentialQuery when eager-loading is set.
	Edges        DesktopModelCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DesktopModelCredentialEdges holds the relations/edges for other nodes in the graph.
type DesktopModelCredentialEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopModelCredentialEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopModelCredentialEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopModelCredentialEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopModelCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktopmodelcredential.FieldID, desktopmodelcredential.FieldUserID, desktopmodelcredential.FieldTokenVersion, desktopmodelcredential.FieldGroupID, desktopmodelcredential.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case desktopmodelcredential.FieldDeviceID, desktopmodelcredential.FieldConnectionGrantID, desktopmodelcredential.FieldSessionFamilyID, desktopmodelcredential.FieldModelID, desktopmodelcredential.FieldRevokeReason:
			values[i] = new(sql.NullString)
		case desktopmodelcredential.FieldCreatedAt, desktopmodelcredential.FieldUpdatedAt, desktopmodelcredential.FieldExpiresAt, desktopmodelcredential.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopModelCredential fields.
func (_m *DesktopModelCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktopmodelcredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktopmodelcredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case desktopmodelcredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case desktopmodelcredential.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case desktopmodelcredential.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case desktopmodelcredential.FieldConnectionGrantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field connection_grant_id", values[i])
			} else if value.Valid {
				_m.ConnectionGrantID = value.String
			}
		case desktopmodelcredential.FieldSessionFamilyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_family_id", values[i])
			} else if value.Valid {
				_m.SessionFamilyID = value.String
			}
		case desktopmodelcredential.FieldTokenVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_version", values[i])
			} else if value.Valid {
				_m.TokenVersion = value.Int64
			}
		case desktopmodelcredential.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case desktopmodelcredential.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case desktopmodelcredential.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case desktopmodelcredential.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case desktopmodelcredential.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case desktopmodelcredential.FieldRevokeReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revoke_reason", values[i])
			} else if value.Valid {
				_m.RevokeReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopModelCredential.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopModelCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the DesktopModelCredential entity.
func (_m *DesktopModelCredential) QueryGroup() *GroupQuery {
	return NewDesktopModelCredentialClient(_m.config).QueryGroup(_m)
}

// QueryUser queries the "user" edge of the DesktopModelCredential entity.
func (_m *DesktopModelCredential) QueryUser() *UserQuery {
	return NewDesktopModelCredentialClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the DesktopModelCredential entity.
func (_m *DesktopModelCredential) QueryAPIKey() *APIKeyQuery {
	return NewDesktopModelCredentialClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this DesktopModelCredential.
// Note that you need to call DesktopModelCredential.Unwrap() before calling this method if this DesktopModelCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopModelCredential) Update() *DesktopModelCredentialUpdateOne {
	return NewDesktopModelCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopModelCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopModelCredential) Unwrap() *DesktopModelCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopModelCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopModelCredential) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopModelCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("connection_grant_id=")
	builder.WriteString(_m.ConnectionGrantID)
	builder.WriteString(", ")
	builder.WriteString("session_family_id=")
	builder.WriteString(_m.SessionFamilyID)
	builder.WriteString(", ")
	builder.WriteString("token_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenVersion))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revoke_reason=")
	builder.WriteString(_m.RevokeReason)
	builder.WriteByte(')')
	return builder.String()
}

// DesktopModelCredentials is a parsable slice of DesktopModelCredential.
type DesktopModelCredentials []*DesktopModelCredential
