// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopmodelcredential"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopModelCredentialQuery is the builder for querying DesktopModelCredential entities.
type DesktopModelCredentialQuery struct {
	config
	ctx        *QueryContext
	order      []desktopmodelcredential.OrderOption
	inters     []Interceptor
	predicates []predicate.DesktopModelCredential
	withGroup  *GroupQuery
	withUser   *UserQuery
	withAPIKey *APIKeyQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DesktopModelCredentialQuery builder.
func (_q *DesktopModelCredentialQuery) Where(ps ...predicate.DesktopModelCredential) *DesktopModelCredentialQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DesktopModelCredentialQuery) Limit(limit int) *DesktopModelCredentialQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DesktopModelCredentialQuery) Offset(offset int) *DesktopModelCredentialQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DesktopModelCredentialQuery) Unique(unique bool) *DesktopModelCredentialQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DesktopModelCredentialQuery) Order(o ...desktopmodelcredential.OrderOption) *DesktopModelCredentialQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *DesktopModelCredentialQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopmodelcredential.Table, desktopmodelcredential.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, desktopmodelcredential.GroupTable, desktopmodelcredential.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *DesktopModelCredentialQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopmodelcredential.Table, desktopmodelcredential.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, desktopmodelcredential.UserTable, desktopmodelcredential.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAPIKey chains the current query on the "api_key" edge.
func (_q *DesktopModelCredentialQuery) QueryAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopmodelcredential.Table, desktopmodelcredential.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, desktopmodelcredential.APIKeyTable, desktopmodelcredential.APIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DesktopModelCredential entity from the query.
// Returns a *NotFoundError when no DesktopModelCredential was found.
func (_q *DesktopModelCredentialQuery) First(ctx context.Context) (*DesktopModelCredential, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{desktopmodelcredential.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) FirstX(ctx context.Context) *DesktopModelCredential {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DesktopModelCredential ID from the query.
// Returns a *NotFoundError when no DesktopModelCredential ID was found.
func (_q *DesktopModelCredentialQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{desktopmodelcredential.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DesktopModelCredential entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DesktopModelCredential entity is found.
// Returns a *NotFoundError when no DesktopModelCredential entities are found.
func (_q *DesktopModelCredentialQuery) Only(ctx context.Context) (*DesktopModelCredential, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{desktopmodelcredential.Label}
	default:
		return nil, &NotSingularError{desktopmodelcredential.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) OnlyX(ctx context.Context) *DesktopModelCredential {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DesktopModelCredential ID in the query.
// Returns a *NotSingularError when more than one DesktopModelCredential ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DesktopModelCredentialQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{desktopmodelcredential.Label}
	default:
		err = &NotSingularError{desktopmodelcredential.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DesktopModelCredentials.
func (_q *DesktopModelCredentialQuery) All(ctx context.Context) ([]*DesktopModelCredential, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DesktopModelCredential, *DesktopModelCredentialQuery]()
	return withInterceptors[[]*DesktopModelCredential](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) AllX(ctx context.Context) []*DesktopModelCredential {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DesktopModelCredential IDs.
func (_q *DesktopModelCredentialQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(desktopmodelcredential.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DesktopModelCredentialQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DesktopModelCredentialQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DesktopModelCredentialQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DesktopModelCredentialQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DesktopModelCredentialQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DesktopModelCredentialQuery) Clone() *DesktopModelCredentialQuery {
	if _q == nil {
		return nil
	}
	return &DesktopModelCredentialQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]desktopmodelcredential.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.DesktopModelCredential{}, _q.predicates...),
		withGroup:  _q.withGroup.Clone(),
		withUser:   _q.withUser.Clone(),
		withAPIKey: _q.withAPIKey.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopModelCredentialQuery) WithGroup(opts ...func(*GroupQuery)) *DesktopModelCredentialQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopModelCredentialQuery) WithUser(opts ...func(*UserQuery)) *DesktopModelCredentialQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopModelCredentialQuery) WithAPIKey(opts ...func(*APIKeyQuery)) *DesktopModelCredentialQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKey = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DesktopModelCredential.Query().
//		GroupBy(desktopmodelcredential.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DesktopModelCredentialQuery) GroupBy(field string, fields ...string) *DesktopModelCredentialGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DesktopModelCredentialGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = desktopmodelcredential.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DesktopModelCredential.Query().
//		Select(desktopmodelcredential.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *DesktopModelCredentialQuery) Select(fields ...string) *DesktopModelCredentialSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DesktopModelCredentialSelect{DesktopModelCredentialQuery: _q}
	sbuild.label = desktopmodelcredential.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DesktopModelCredentialSelect configured with the given aggregations.
func (_q *DesktopModelCredentialQuery) Aggregate(fns ...AggregateFunc) *DesktopModelCredentialSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DesktopModelCredentialQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !desktopmodelcredential.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DesktopModelCredentialQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DesktopModelCredential, error) {
	var (
		nodes       = []*DesktopModelCredential{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withGroup != nil,
			_q.withUser != nil,
			_q.withAPIKey != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DesktopModelCredential).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DesktopModelCredential{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *DesktopModelCredential, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *DesktopModelCredential, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAPIKey; query != nil {
		if err := _q.loadAPIKey(ctx, query, nodes, nil,
			func(n *DesktopModelCredential, e *APIKey) { n.Edges.APIKey = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DesktopModelCredentialQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*DesktopModelCredential, init func(*DesktopModelCredential), assign func(*DesktopModelCredential, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*DesktopModelCredential)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DesktopModelCredentialQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*DesktopModelCredential, init func(*DesktopModelCredential), assign func(*DesktopModelCredential, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*DesktopModelCredential)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DesktopModelCredentialQuery) loadAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*DesktopModelCredential, init func(*DesktopModelCredential), assign func(*DesktopModelCredential, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*DesktopModelCredential)
	for i := range nodes {
		fk := nodes[i].APIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DesktopModelCredentialQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DesktopModelCredentialQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(desktopmodelcredential.Table, desktopmodelcredential.Columns, sqlgraph.NewFieldSpec(desktopmodelcredential.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopmodelcredential.FieldID)
		for i := range fields {
			if fields[i] != desktopmodelcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(desktopmodelcredential.FieldGroupID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(desktopmodelcredential.FieldUserID)
		}
		if _q.withAPIKey != nil {
			_spec.Node.AddColumnOnce(desktopmodelcredential.FieldAPIKeyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DesktopModelCredentialQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(desktopmodelcredential.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = desktopmodelcredential.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *DesktopModelCredentialQuery) ForUpdate(opts ...sql.LockOption) *DesktopModelCredentialQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *DesktopModelCredentialQuery) ForShare(opts ...sql.LockOption) *DesktopModelCredentialQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// DesktopModelCredentialGroupBy is the group-by builder for DesktopModelCredential entities.
type DesktopModelCredentialGroupBy struct {
	selector
	build *DesktopModelCredentialQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DesktopModelCredentialGroupBy) Aggregate(fns ...AggregateFunc) *DesktopModelCredentialGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DesktopModelCredentialGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DesktopModelCredentialQuery, *DesktopModelCredentialGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DesktopModelCredentialGroupBy) sqlScan(ctx context.Context, root *DesktopModelCredentialQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DesktopModelCredentialSelect is the builder for selecting fields of DesktopModelCredential entities.
type DesktopModelCredentialSelect struct {
	*DesktopModelCredentialQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DesktopModelCredentialSelect) Aggregate(fns ...AggregateFunc) *DesktopModelCredentialSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DesktopModelCredentialSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DesktopModelCredentialQuery, *DesktopModelCredentialSelect](ctx, _s.DesktopModelCredentialQuery, _s, _s.inters, v)
}

func (_s *DesktopModelCredentialSelect) sqlScan(ctx context.Context, root *DesktopModelCredentialQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
