// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopmodelcredential"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopModelCredentialDelete is the builder for deleting a DesktopModelCredential entity.
type DesktopModelCredentialDelete struct {
	config
	hooks    []Hook
	mutation *DesktopModelCredentialMutation
}

// Where appends a list predicates to the DesktopModelCredentialDelete builder.
func (_d *DesktopModelCredentialDelete) Where(ps ...predicate.DesktopModelCredential) *DesktopModelCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DesktopModelCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DesktopModelCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DesktopModelCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(desktopmodelcredential.Table, sqlgraph.NewFieldSpec(desktopmodelcredential.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DesktopModelCredentialDeleteOne is the builder for deleting a single DesktopModelCredential entity.
type DesktopModelCredentialDeleteOne struct {
	_d *DesktopModelCredentialDelete
}

// Where appends a list predicates to the DesktopModelCredentialDelete builder.
func (_d *DesktopModelCredentialDeleteOne) Where(ps ...predicate.DesktopModelCredential) *DesktopModelCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DesktopModelCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{desktopmodelcredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DesktopModelCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
