// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopmodelcredential"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopModelCredentialUpdate is the builder for updating DesktopModelCredential entities.
type DesktopModelCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopModelCredentialMutation
}

// Where appends a list predicates to the DesktopModelCredentialUpdate builder.
func (_u *DesktopModelCredentialUpdate) Where(ps ...predicate.DesktopModelCredential) *DesktopModelCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopModelCredentialUpdate) SetUpdatedAt(v time.Time) *DesktopModelCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopModelCredentialUpdate) SetUserID(v int64) *DesktopModelCredentialUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableUserID(v *int64) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopModelCredentialUpdate) SetDeviceID(v string) *DesktopModelCredentialUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableDeviceID(v *string) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetConnectionGrantID sets the "connection_grant_id" field.
func (_u *DesktopModelCredentialUpdate) SetConnectionGrantID(v string) *DesktopModelCredentialUpdate {
	_u.mutation.SetConnectionGrantID(v)
	return _u
}

// SetNillableConnectionGrantID sets the "connection_grant_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableConnectionGrantID(v *string) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetConnectionGrantID(*v)
	}
	return _u
}

// SetSessionFamilyID sets the "session_family_id" field.
func (_u *DesktopModelCredentialUpdate) SetSessionFamilyID(v string) *DesktopModelCredentialUpdate {
	_u.mutation.SetSessionFamilyID(v)
	return _u
}

// SetNillableSessionFamilyID sets the "session_family_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableSessionFamilyID(v *string) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetSessionFamilyID(*v)
	}
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *DesktopModelCredentialUpdate) SetTokenVersion(v int64) *DesktopModelCredentialUpdate {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableTokenVersion(v *int64) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *DesktopModelCredentialUpdate) AddTokenVersion(v int64) *DesktopModelCredentialUpdate {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DesktopModelCredentialUpdate) SetGroupID(v int64) *DesktopModelCredentialUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableGroupID(v *int64) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *DesktopModelCredentialUpdate) SetModelID(v string) *DesktopModelCredentialUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableModelID(v *string) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *DesktopModelCredentialUpdate) SetAPIKeyID(v int64) *DesktopModelCredentialUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableAPIKeyID(v *int64) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopModelCredentialUpdate) SetExpiresAt(v time.Time) *DesktopModelCredentialUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableExpiresAt(v *time.Time) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopModelCredentialUpdate) SetRevokedAt(v time.Time) *DesktopModelCredentialUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableRevokedAt(v *time.Time) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopModelCredentialUpdate) ClearRevokedAt() *DesktopModelCredentialUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *DesktopModelCredentialUpdate) SetRevokeReason(v string) *DesktopModelCredentialUpdate {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdate) SetNillableRevokeReason(v *string) *DesktopModelCredentialUpdate {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (_u *DesktopModelCredentialUpdate) ClearRevokeReason() *DesktopModelCredentialUpdate {
	_u.mutation.ClearRevokeReason()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DesktopModelCredentialUpdate) SetGroup(v *Group) *DesktopModelCredentialUpdate {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DesktopModelCredentialUpdate) SetUser(v *User) *DesktopModelCredentialUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *DesktopModelCredentialUpdate) SetAPIKey(v *APIKey) *DesktopModelCredentialUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the DesktopModelCredentialMutation object of the builder.
func (_u *DesktopModelCredentialUpdate) Mutation() *DesktopModelCredentialMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DesktopModelCredentialUpdate) ClearGroup() *DesktopModelCredentialUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DesktopModelCredentialUpdate) ClearUser() *DesktopModelCredentialUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *DesktopModelCredentialUpdate) ClearAPIKey() *DesktopModelCredentialUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopModelCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopModelCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopModelCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopModelCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopModelCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopmodelcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopModelCredentialUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := desktopmodelcredential.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConnectionGrantID(); ok {
		if err := desktopmodelcredential.ConnectionGrantIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_grant_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.connection_grant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionFamilyID(); ok {
		if err := desktopmodelcredential.SessionFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "session_family_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.session_family_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelID(); ok {
		if err := desktopmodelcredential.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevokeReason(); ok {
		if err := desktopmodelcredential.RevokeReasonValidator(v); err != nil {
			return &ValidationError{Name: "revoke_reason", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.revoke_reason": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopModelCredential.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopModelCredential.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopModelCredential.api_key"`)
	}
	return nil
}

func (_u *DesktopModelCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopmodelcredential.Table, desktopmodelcredential.Columns, sqlgraph.NewFieldSpec(desktopmodelcredential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(desktopmodelcredential.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConnectionGrantID(); ok {
		_spec.SetField(desktopmodelcredential.FieldConnectionGrantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionFamilyID(); ok {
		_spec.SetField(desktopmodelcredential.FieldSessionFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(desktopmodelcredential.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(desktopmodelcredential.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(desktopmodelcredential.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopmodelcredential.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(desktopmodelcredential.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.RevokeReasonCleared() {
		_spec.ClearField(desktopmodelcredential.FieldRevokeReason, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.GroupTable,
			Columns: []string{desktopmodelcredential.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.GroupTable,
			Columns: []string{desktopmodelcredential.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.UserTable,
			Columns: []string{desktopmodelcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.UserTable,
			Columns: []string{desktopmodelcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.APIKeyTable,
			Columns: []string{desktopmodelcredential.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.APIKeyTable,
			Columns: []string{desktopmodelcredential.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopmodelcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopModelCredentialUpdateOne is the builder for updating a single DesktopModelCredential entity.
type DesktopModelCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopModelCredentialMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopModelCredentialUpdateOne) SetUpdatedAt(v time.Time) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetUserID(v int64) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableUserID(v *int64) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetDeviceID(v string) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableDeviceID(v *string) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetConnectionGrantID sets the "connection_grant_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetConnectionGrantID(v string) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetConnectionGrantID(v)
	return _u
}

// SetNillableConnectionGrantID sets the "connection_grant_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableConnectionGrantID(v *string) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetConnectionGrantID(*v)
	}
	return _u
}

// SetSessionFamilyID sets the "session_family_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetSessionFamilyID(v string) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetSessionFamilyID(v)
	return _u
}

// SetNillableSessionFamilyID sets the "session_family_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableSessionFamilyID(v *string) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetSessionFamilyID(*v)
	}
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *DesktopModelCredentialUpdateOne) SetTokenVersion(v int64) *DesktopModelCredentialUpdateOne {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableTokenVersion(v *int64) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *DesktopModelCredentialUpdateOne) AddTokenVersion(v int64) *DesktopModelCredentialUpdateOne {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetGroupID(v int64) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableGroupID(v *int64) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetModelID(v string) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableModelID(v *string) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *DesktopModelCredentialUpdateOne) SetAPIKeyID(v int64) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableAPIKeyID(v *int64) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopModelCredentialUpdateOne) SetExpiresAt(v time.Time) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableExpiresAt(v *time.Time) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopModelCredentialUpdateOne) SetRevokedAt(v time.Time) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableRevokedAt(v *time.Time) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopModelCredentialUpdateOne) ClearRevokedAt() *DesktopModelCredentialUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *DesktopModelCredentialUpdateOne) SetRevokeReason(v string) *DesktopModelCredentialUpdateOne {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *DesktopModelCredentialUpdateOne) SetNillableRevokeReason(v *string) *DesktopModelCredentialUpdateOne {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (_u *DesktopModelCredentialUpdateOne) ClearRevokeReason() *DesktopModelCredentialUpdateOne {
	_u.mutation.ClearRevokeReason()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DesktopModelCredentialUpdateOne) SetGroup(v *Group) *DesktopModelCredentialUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DesktopModelCredentialUpdateOne) SetUser(v *User) *DesktopModelCredentialUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *DesktopModelCredentialUpdateOne) SetAPIKey(v *APIKey) *DesktopModelCredentialUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the DesktopModelCredentialMutation object of the builder.
func (_u *DesktopModelCredentialUpdateOne) Mutation() *DesktopModelCredentialMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DesktopModelCredentialUpdateOne) ClearGroup() *DesktopModelCredentialUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DesktopModelCredentialUpdateOne) ClearUser() *DesktopModelCredentialUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *DesktopModelCredentialUpdateOne) ClearAPIKey() *DesktopModelCredentialUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the DesktopModelCredentialUpdate builder.
func (_u *DesktopModelCredentialUpdateOne) Where(ps ...predicate.DesktopModelCredential) *DesktopModelCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopModelCredentialUpdateOne) Select(field string, fields ...string) *DesktopModelCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopModelCredential entity.
func (_u *DesktopModelCredentialUpdateOne) Save(ctx context.Context) (*DesktopModelCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopModelCredentialUpdateOne) SaveX(ctx context.Context) *DesktopModelCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopModelCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopModelCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopModelCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopmodelcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopModelCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := desktopmodelcredential.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConnectionGrantID(); ok {
		if err := desktopmodelcredential.ConnectionGrantIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_grant_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.connection_grant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionFamilyID(); ok {
		if err := desktopmodelcredential.SessionFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "session_family_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.session_family_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelID(); ok {
		if err := desktopmodelcredential.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevokeReason(); ok {
		if err := desktopmodelcredential.RevokeReasonValidator(v); err != nil {
			return &ValidationError{Name: "revoke_reason", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.revoke_reason": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopModelCredential.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopModelCredential.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopModelCredential.api_key"`)
	}
	return nil
}

func (_u *DesktopModelCredentialUpdateOne) sqlSave(ctx context.Context) (_node *DesktopModelCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopmodelcredential.Table, desktopmodelcredential.Columns, sqlgraph.NewFieldSpec(desktopmodelcredential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopModelCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopmodelcredential.FieldID)
		for _, f := range fields {
			if !desktopmodelcredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopmodelcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(desktopmodelcredential.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConnectionGrantID(); ok {
		_spec.SetField(desktopmodelcredential.FieldConnectionGrantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionFamilyID(); ok {
		_spec.SetField(desktopmodelcredential.FieldSessionFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(desktopmodelcredential.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(desktopmodelcredential.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(desktopmodelcredential.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopmodelcredential.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(desktopmodelcredential.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.RevokeReasonCleared() {
		_spec.ClearField(desktopmodelcredential.FieldRevokeReason, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.GroupTable,
			Columns: []string{desktopmodelcredential.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.GroupTable,
			Columns: []string{desktopmodelcredential.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.UserTable,
			Columns: []string{desktopmodelcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.UserTable,
			Columns: []string{desktopmodelcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.APIKeyTable,
			Columns: []string{desktopmodelcredential.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.APIKeyTable,
			Columns: []string{desktopmodelcredential.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopModelCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopmodelcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
