// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopmodelcredential"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopModelCredentialCreate is the builder for creating a DesktopModelCredential entity.
type DesktopModelCredentialCreate struct {
	config
	mutation *DesktopModelCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopModelCredentialCreate) SetCreatedAt(v time.Time) *DesktopModelCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopModelCredentialCreate) SetNillableCreatedAt(v *time.Time) *DesktopModelCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopModelCredentialCreate) SetUpdatedAt(v time.Time) *DesktopModelCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopModelCredentialCreate) SetNillableUpdatedAt(v *time.Time) *DesktopModelCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DesktopModelCredentialCreate) SetUserID(v int64) *DesktopModelCredentialCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *DesktopModelCredentialCreate) SetDeviceID(v string) *DesktopModelCredentialCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetConnectionGrantID sets the "connection_grant_id" field.
func (_c *DesktopModelCredentialCreate) SetConnectionGrantID(v string) *DesktopModelCredentialCreate {
	_c.mutation.SetConnectionGrantID(v)
	return _c
}

// SetSessionFamilyID sets the "session_family_id" field.
func (_c *DesktopModelCredentialCreate) SetSessionFamilyID(v string) *DesktopModelCredentialCreate {
	_c.mutation.SetSessionFamilyID(v)
	return _c
}

// SetTokenVersion sets the "token_version" field.
func (_c *DesktopModelCredentialCreate) SetTokenVersion(v int64) *DesktopModelCredentialCreate {
	_c.mutation.SetTokenVersion(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DesktopModelCredentialCreate) SetGroupID(v int64) *DesktopModelCredentialCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *DesktopModelCredentialCreate) SetModelID(v string) *DesktopModelCredentialCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *DesktopModelCredentialCreate) SetAPIKeyID(v int64) *DesktopModelCredentialCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DesktopModelCredentialCreate) SetExpiresAt(v time.Time) *DesktopModelCredentialCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *DesktopModelCredentialCreate) SetRevokedAt(v time.Time) *DesktopModelCredentialCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *DesktopModelCredentialCreate) SetNillableRevokedAt(v *time.Time) *DesktopModelCredentialCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevokeReason sets the "revoke_reason" field.
func (_c *DesktopModelCredentialCreate) SetRevokeReason(v string) *DesktopModelCredentialCreate {
	_c.mutation.SetRevokeReason(v)
	return _c
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_c *DesktopModelCredentialCreate) SetNillableRevokeReason(v *string) *DesktopModelCredentialCreate {
	if v != nil {
		_c.SetRevokeReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DesktopModelCredentialCreate) SetID(v int64) *DesktopModelCredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *DesktopModelCredentialCreate) SetGroup(v *Group) *DesktopModelCredentialCreate {
	return _c.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *DesktopModelCredentialCreate) SetUser(v *User) *DesktopModelCredentialCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *DesktopModelCredentialCreate) SetAPIKey(v *APIKey) *DesktopModelCredentialCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the DesktopModelCredentialMutation object of the builder.
func (_c *DesktopModelCredentialCreate) Mutation() *DesktopModelCredentialMutation {
	return _c.mutation
}

// Save creates the DesktopModelCredential in the database.
func (_c *DesktopModelCredentialCreate) Save(ctx context.Context) (*DesktopModelCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopModelCredentialCreate) SaveX(ctx context.Context) *DesktopModelCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopModelCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopModelCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopModelCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := desktopmodelcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := desktopmodelcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopModelCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopModelCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopModelCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DesktopModelCredential.user_id"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DesktopModelCredential.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := desktopmodelcredential.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConnectionGrantID(); !ok {
		return &ValidationError{Name: "connection_grant_id", err: errors.New(`ent: missing required field "DesktopModelCredential.connection_grant_id"`)}
	}
	if v, ok := _c.mutation.ConnectionGrantID(); ok {
		if err := desktopmodelcredential.ConnectionGrantIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_grant_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.connection_grant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionFamilyID(); !ok {
		return &ValidationError{Name: "session_family_id", err: errors.New(`ent: missing required field "DesktopModelCredential.session_family_id"`)}
	}
	if v, ok := _c.mutation.SessionFamilyID(); ok {
		if err := desktopmodelcredential.SessionFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "session_family_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.session_family_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenVersion(); !ok {
		return &ValidationError{Name: "token_version", err: errors.New(`ent: missing required field "DesktopModelCredential.token_version"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "DesktopModelCredential.group_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "DesktopModelCredential.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := desktopmodelcredential.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "DesktopModelCredential.api_key_id"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "DesktopModelCredential.expires_at"`)}
	}
	if v, ok := _c.mutation.RevokeReason(); ok {
		if err := desktopmodelcredential.RevokeReasonValidator(v); err != nil {
			return &ValidationError{Name: "revoke_reason", err: fmt.Errorf(`ent: validator failed for field "DesktopModelCredential.revoke_reason": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "DesktopModelCredential.group"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DesktopModelCredential.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "DesktopModelCredential.api_key"`)}
	}
	return nil
}

func (_c *DesktopModelCredentialCreate) sqlSave(ctx context.Context) (*DesktopModelCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopModelCredentialCreate) createSpec() (*DesktopModelCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopModelCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopmodelcredential.Table, sqlgraph.NewFieldSpec(desktopmodelcredential.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(desktopmodelcredential.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.ConnectionGrantID(); ok {
		_spec.SetField(desktopmodelcredential.FieldConnectionGrantID, field.TypeString, value)
		_node.ConnectionGrantID = value
	}
	if value, ok := _c.mutation.SessionFamilyID(); ok {
		_spec.SetField(desktopmodelcredential.FieldSessionFamilyID, field.TypeString, value)
		_node.SessionFamilyID = value
	}
	if value, ok := _c.mutation.TokenVersion(); ok {
		_spec.SetField(desktopmodelcredential.FieldTokenVersion, field.TypeInt64, value)
		_node.TokenVersion = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(desktopmodelcredential.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(desktopmodelcredential.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevokeReason(); ok {
		_spec.SetField(desktopmodelcredential.FieldRevokeReason, field.TypeString, value)
		_node.RevokeReason = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.GroupTable,
			Columns: []string{desktopmodelcredential.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.UserTable,
			Columns: []string{desktopmodelcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopmodelcredential.APIKeyTable,
			Columns: []string{desktopmodelcredential.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopModelCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopModelCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopModelCredentialCreate) OnConflict(opts ...sql.ConflictOption) *DesktopModelCredentialUpsertOne {
	_c.conflict = opts
	return &DesktopModelCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopModelCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopModelCredentialCreate) OnConflictColumns(columns ...string) *DesktopModelCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopModelCredentialUpsertOne{
		create: _c,
	}
}

type (
	// DesktopModelCredentialUpsertOne is the builder for "upsert"-ing
	//  one DesktopModelCredential node.
	DesktopModelCredentialUpsertOne struct {
		create *DesktopModelCredentialCreate
	}

	// DesktopModelCredentialUpsert is the "OnConflict" setter.
	DesktopModelCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopModelCredentialUpsert) SetUpdatedAt(v time.Time) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateUpdatedAt() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DesktopModelCredentialUpsert) SetUserID(v int64) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateUserID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldUserID)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopModelCredentialUpsert) SetDeviceID(v string) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateDeviceID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldDeviceID)
	return u
}

// SetConnectionGrantID sets the "connection_grant_id" field.
func (u *DesktopModelCredentialUpsert) SetConnectionGrantID(v string) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldConnectionGrantID, v)
	return u
}

// UpdateConnectionGrantID sets the "connection_grant_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateConnectionGrantID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldConnectionGrantID)
	return u
}

// SetSessionFamilyID sets the "session_family_id" field.
func (u *DesktopModelCredentialUpsert) SetSessionFamilyID(v string) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldSessionFamilyID, v)
	return u
}

// UpdateSessionFamilyID sets the "session_family_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateSessionFamilyID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldSessionFamilyID)
	return u
}

// SetTokenVersion sets the "token_version" field.
func (u *DesktopModelCredentialUpsert) SetTokenVersion(v int64) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldTokenVersion, v)
	return u
}

// UpdateTokenVersion sets the "token_version" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateTokenVersion() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldTokenVersion)
	return u
}

// AddTokenVersion adds v to the "token_version" field.
func (u *DesktopModelCredentialUpsert) AddTokenVersion(v int64) *DesktopModelCredentialUpsert {
	u.Add(desktopmodelcredential.FieldTokenVersion, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *DesktopModelCredentialUpsert) SetGroupID(v int64) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateGroupID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldGroupID)
	return u
}

// SetModelID sets the "model_id" field.
func (u *DesktopModelCredentialUpsert) SetModelID(v string) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateModelID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldModelID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DesktopModelCredentialUpsert) SetAPIKeyID(v int64) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateAPIKeyID() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldAPIKeyID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopModelCredentialUpsert) SetExpiresAt(v time.Time) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateExpiresAt() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldExpiresAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopModelCredentialUpsert) SetRevokedAt(v time.Time) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateRevokedAt() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopModelCredentialUpsert) ClearRevokedAt() *DesktopModelCredentialUpsert {
	u.SetNull(desktopmodelcredential.FieldRevokedAt)
	return u
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *DesktopModelCredentialUpsert) SetRevokeReason(v string) *DesktopModelCredentialUpsert {
	u.Set(desktopmodelcredential.FieldRevokeReason, v)
	return u
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsert) UpdateRevokeReason() *DesktopModelCredentialUpsert {
	u.SetExcluded(desktopmodelcredential.FieldRevokeReason)
	return u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (u *DesktopModelCredentialUpsert) ClearRevokeReason() *DesktopModelCredentialUpsert {
	u.SetNull(desktopmodelcredential.FieldRevokeReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DesktopModelCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(desktopmodelcredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DesktopModelCredentialUpsertOne) UpdateNewValues() *DesktopModelCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(desktopmodelcredential.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktopmodelcredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopModelCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopModelCredentialUpsertOne) Ignore() *DesktopModelCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopModelCredentialUpsertOne) DoNothing() *DesktopModelCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopModelCredentialCreate.OnConflict
// documentation for more info.
func (u *DesktopModelCredentialUpsertOne) Update(set func(*DesktopModelCredentialUpsert)) *DesktopModelCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopModelCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopModelCredentialUpsertOne) SetUpdatedAt(v time.Time) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateUpdatedAt() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DesktopModelCredentialUpsertOne) SetUserID(v int64) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateUserID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateUserID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopModelCredentialUpsertOne) SetDeviceID(v string) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateDeviceID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateDeviceID()
	})
}

// SetConnectionGrantID sets the "connection_grant_id" field.
func (u *DesktopModelCredentialUpsertOne) SetConnectionGrantID(v string) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetConnectionGrantID(v)
	})
}

// UpdateConnectionGrantID sets the "connection_grant_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateConnectionGrantID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateConnectionGrantID()
	})
}

// SetSessionFamilyID sets the "session_family_id" field.
func (u *DesktopModelCredentialUpsertOne) SetSessionFamilyID(v string) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetSessionFamilyID(v)
	})
}

// UpdateSessionFamilyID sets the "session_family_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateSessionFamilyID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateSessionFamilyID()
	})
}

// SetTokenVersion sets the "token_version" field.
func (u *DesktopModelCredentialUpsertOne) SetTokenVersion(v int64) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetTokenVersion(v)
	})
}

// AddTokenVersion adds v to the "token_version" field.
func (u *DesktopModelCredentialUpsertOne) AddTokenVersion(v int64) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.AddTokenVersion(v)
	})
}

// UpdateTokenVersion sets the "token_version" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateTokenVersion() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateTokenVersion()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DesktopModelCredentialUpsertOne) SetGroupID(v int64) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateGroupID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelID sets the "model_id" field.
func (u *DesktopModelCredentialUpsertOne) SetModelID(v string) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateModelID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateModelID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DesktopModelCredentialUpsertOne) SetAPIKeyID(v int64) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateAPIKeyID() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopModelCredentialUpsertOne) SetExpiresAt(v time.Time) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateExpiresAt() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopModelCredentialUpsertOne) SetRevokedAt(v time.Time) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateRevokedAt() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopModelCredentialUpsertOne) ClearRevokedAt() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *DesktopModelCredentialUpsertOne) SetRevokeReason(v string) *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetRevokeReason(v)
	})
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertOne) UpdateRevokeReason() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateRevokeReason()
	})
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (u *DesktopModelCredentialUpsertOne) ClearRevokeReason() *DesktopModelCredentialUpsertOne {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.ClearRevokeReason()
	})
}

// Exec executes the query.
func (u *DesktopModelCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopModelCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopModelCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopModelCredentialUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopModelCredentialUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopModelCredentialCreateBulk is the builder for creating many DesktopModelCredential entities in bulk.
type DesktopModelCredentialCreateBulk struct {
	config
	err      error
	builders []*DesktopModelCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopModelCredential entities in the database.
func (_c *DesktopModelCredentialCreateBulk) Save(ctx context.Context) ([]*DesktopModelCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopModelCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopModelCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopModelCredentialCreateBulk) SaveX(ctx context.Context) []*DesktopModelCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopModelCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopModelCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopModelCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopModelCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopModelCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopModelCredentialUpsertBulk {
	_c.conflict = opts
	return &DesktopModelCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopModelCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopModelCredentialCreateBulk) OnConflictColumns(columns ...string) *DesktopModelCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopModelCredentialUpsertBulk{
		create: _c,
	}
}

// DesktopModelCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopModelCredential nodes.
type DesktopModelCredentialUpsertBulk struct {
	create *DesktopModelCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopModelCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(desktopmodelcredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DesktopModelCredentialUpsertBulk) UpdateNewValues() *DesktopModelCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(desktopmodelcredential.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktopmodelcredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopModelCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopModelCredentialUpsertBulk) Ignore() *DesktopModelCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopModelCredentialUpsertBulk) DoNothing() *DesktopModelCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopModelCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopModelCredentialUpsertBulk) Update(set func(*DesktopModelCredentialUpsert)) *DesktopModelCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopModelCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopModelCredentialUpsertBulk) SetUpdatedAt(v time.Time) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateUpdatedAt() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetUserID(v int64) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateUserID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateUserID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetDeviceID(v string) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateDeviceID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateDeviceID()
	})
}

// SetConnectionGrantID sets the "connection_grant_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetConnectionGrantID(v string) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetConnectionGrantID(v)
	})
}

// UpdateConnectionGrantID sets the "connection_grant_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateConnectionGrantID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateConnectionGrantID()
	})
}

// SetSessionFamilyID sets the "session_family_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetSessionFamilyID(v string) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetSessionFamilyID(v)
	})
}

// UpdateSessionFamilyID sets the "session_family_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateSessionFamilyID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateSessionFamilyID()
	})
}

// SetTokenVersion sets the "token_version" field.
func (u *DesktopModelCredentialUpsertBulk) SetTokenVersion(v int64) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetTokenVersion(v)
	})
}

// AddTokenVersion adds v to the "token_version" field.
func (u *DesktopModelCredentialUpsertBulk) AddTokenVersion(v int64) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.AddTokenVersion(v)
	})
}

// UpdateTokenVersion sets the "token_version" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateTokenVersion() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateTokenVersion()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetGroupID(v int64) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateGroupID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelID sets the "model_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetModelID(v string) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateModelID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateModelID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DesktopModelCredentialUpsertBulk) SetAPIKeyID(v int64) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateAPIKeyID() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopModelCredentialUpsertBulk) SetExpiresAt(v time.Time) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateExpiresAt() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopModelCredentialUpsertBulk) SetRevokedAt(v time.Time) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateRevokedAt() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopModelCredentialUpsertBulk) ClearRevokedAt() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *DesktopModelCredentialUpsertBulk) SetRevokeReason(v string) *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.SetRevokeReason(v)
	})
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *DesktopModelCredentialUpsertBulk) UpdateRevokeReason() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.UpdateRevokeReason()
	})
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (u *DesktopModelCredentialUpsertBulk) ClearRevokeReason() *DesktopModelCredentialUpsertBulk {
	return u.Update(func(s *DesktopModelCredentialUpsert) {
		s.ClearRevokeReason()
	})
}

// Exec executes the query.
func (u *DesktopModelCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopModelCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopModelCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopModelCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
