// Code generated by ent, DO NOT EDIT.

package desktopmodelcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldUserID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldDeviceID, v))
}

// ConnectionGrantID applies equality check predicate on the "connection_grant_id" field. It's identical to ConnectionGrantIDEQ.
func ConnectionGrantID(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldConnectionGrantID, v))
}

// SessionFamilyID applies equality check predicate on the "session_family_id" field. It's identical to SessionFamilyIDEQ.
func SessionFamilyID(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldSessionFamilyID, v))
}

// TokenVersion applies equality check predicate on the "token_version" field. It's identical to TokenVersionEQ.
func TokenVersion(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldTokenVersion, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldGroupID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldModelID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldAPIKeyID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokeReason applies equality check predicate on the "revoke_reason" field. It's identical to RevokeReasonEQ.
func RevokeReason(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldRevokeReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldUserID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContainsFold(FieldDeviceID, v))
}

// ConnectionGrantIDEQ applies the EQ predicate on the "connection_grant_id" field.
func ConnectionGrantIDEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldConnectionGrantID, v))
}

// ConnectionGrantIDNEQ applies the NEQ predicate on the "connection_grant_id" field.
func ConnectionGrantIDNEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldConnectionGrantID, v))
}

// ConnectionGrantIDIn applies the In predicate on the "connection_grant_id" field.
func ConnectionGrantIDIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldConnectionGrantID, vs...))
}

// ConnectionGrantIDNotIn applies the NotIn predicate on the "connection_grant_id" field.
func ConnectionGrantIDNotIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldConnectionGrantID, vs...))
}

// ConnectionGrantIDGT applies the GT predicate on the "connection_grant_id" field.
func ConnectionGrantIDGT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldConnectionGrantID, v))
}

// ConnectionGrantIDGTE applies the GTE predicate on the "connection_grant_id" field.
func ConnectionGrantIDGTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldConnectionGrantID, v))
}

// ConnectionGrantIDLT applies the LT predicate on the "connection_grant_id" field.
func ConnectionGrantIDLT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldConnectionGrantID, v))
}

// ConnectionGrantIDLTE applies the LTE predicate on the "connection_grant_id" field.
func ConnectionGrantIDLTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldConnectionGrantID, v))
}

// ConnectionGrantIDContains applies the Contains predicate on the "connection_grant_id" field.
func ConnectionGrantIDContains(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContains(FieldConnectionGrantID, v))
}

// ConnectionGrantIDHasPrefix applies the HasPrefix predicate on the "connection_grant_id" field.
func ConnectionGrantIDHasPrefix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasPrefix(FieldConnectionGrantID, v))
}

// ConnectionGrantIDHasSuffix applies the HasSuffix predicate on the "connection_grant_id" field.
func ConnectionGrantIDHasSuffix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasSuffix(FieldConnectionGrantID, v))
}

// ConnectionGrantIDEqualFold applies the EqualFold predicate on the "connection_grant_id" field.
func ConnectionGrantIDEqualFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEqualFold(FieldConnectionGrantID, v))
}

// ConnectionGrantIDContainsFold applies the ContainsFold predicate on the "connection_grant_id" field.
func ConnectionGrantIDContainsFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContainsFold(FieldConnectionGrantID, v))
}

// SessionFamilyIDEQ applies the EQ predicate on the "session_family_id" field.
func SessionFamilyIDEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldSessionFamilyID, v))
}

// SessionFamilyIDNEQ applies the NEQ predicate on the "session_family_id" field.
func SessionFamilyIDNEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldSessionFamilyID, v))
}

// SessionFamilyIDIn applies the In predicate on the "session_family_id" field.
func SessionFamilyIDIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldSessionFamilyID, vs...))
}

// SessionFamilyIDNotIn applies the NotIn predicate on the "session_family_id" field.
func SessionFamilyIDNotIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldSessionFamilyID, vs...))
}

// SessionFamilyIDGT applies the GT predicate on the "session_family_id" field.
func SessionFamilyIDGT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldSessionFamilyID, v))
}

// SessionFamilyIDGTE applies the GTE predicate on the "session_family_id" field.
func SessionFamilyIDGTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldSessionFamilyID, v))
}

// SessionFamilyIDLT applies the LT predicate on the "session_family_id" field.
func SessionFamilyIDLT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldSessionFamilyID, v))
}

// SessionFamilyIDLTE applies the LTE predicate on the "session_family_id" field.
func SessionFamilyIDLTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldSessionFamilyID, v))
}

// SessionFamilyIDContains applies the Contains predicate on the "session_family_id" field.
func SessionFamilyIDContains(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContains(FieldSessionFamilyID, v))
}

// SessionFamilyIDHasPrefix applies the HasPrefix predicate on the "session_family_id" field.
func SessionFamilyIDHasPrefix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasPrefix(FieldSessionFamilyID, v))
}

// SessionFamilyIDHasSuffix applies the HasSuffix predicate on the "session_family_id" field.
func SessionFamilyIDHasSuffix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasSuffix(FieldSessionFamilyID, v))
}

// SessionFamilyIDEqualFold applies the EqualFold predicate on the "session_family_id" field.
func SessionFamilyIDEqualFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEqualFold(FieldSessionFamilyID, v))
}

// SessionFamilyIDContainsFold applies the ContainsFold predicate on the "session_family_id" field.
func SessionFamilyIDContainsFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContainsFold(FieldSessionFamilyID, v))
}

// TokenVersionEQ applies the EQ predicate on the "token_version" field.
func TokenVersionEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldTokenVersion, v))
}

// TokenVersionNEQ applies the NEQ predicate on the "token_version" field.
func TokenVersionNEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldTokenVersion, v))
}

// TokenVersionIn applies the In predicate on the "token_version" field.
func TokenVersionIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldTokenVersion, vs...))
}

// TokenVersionNotIn applies the NotIn predicate on the "token_version" field.
func TokenVersionNotIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldTokenVersion, vs...))
}

// TokenVersionGT applies the GT predicate on the "token_version" field.
func TokenVersionGT(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldTokenVersion, v))
}

// TokenVersionGTE applies the GTE predicate on the "token_version" field.
func TokenVersionGTE(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldTokenVersion, v))
}

// TokenVersionLT applies the LT predicate on the "token_version" field.
func TokenVersionLT(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldTokenVersion, v))
}

// TokenVersionLTE applies the LTE predicate on the "token_version" field.
func TokenVersionLTE(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldTokenVersion, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldGroupID, vs...))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContainsFold(FieldModelID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotNull(FieldRevokedAt))
}

// RevokeReasonEQ applies the EQ predicate on the "revoke_reason" field.
func RevokeReasonEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEQ(FieldRevokeReason, v))
}

// RevokeReasonNEQ applies the NEQ predicate on the "revoke_reason" field.
func RevokeReasonNEQ(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNEQ(FieldRevokeReason, v))
}

// RevokeReasonIn applies the In predicate on the "revoke_reason" field.
func RevokeReasonIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIn(FieldRevokeReason, vs...))
}

// RevokeReasonNotIn applies the NotIn predicate on the "revoke_reason" field.
func RevokeReasonNotIn(vs ...string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotIn(FieldRevokeReason, vs...))
}

// RevokeReasonGT applies the GT predicate on the "revoke_reason" field.
func RevokeReasonGT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGT(FieldRevokeReason, v))
}

// RevokeReasonGTE applies the GTE predicate on the "revoke_reason" field.
func RevokeReasonGTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldGTE(FieldRevokeReason, v))
}

// RevokeReasonLT applies the LT predicate on the "revoke_reason" field.
func RevokeReasonLT(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLT(FieldRevokeReason, v))
}

// RevokeReasonLTE applies the LTE predicate on the "revoke_reason" field.
func RevokeReasonLTE(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldLTE(FieldRevokeReason, v))
}

// RevokeReasonContains applies the Contains predicate on the "revoke_reason" field.
func RevokeReasonContains(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContains(FieldRevokeReason, v))
}

// RevokeReasonHasPrefix applies the HasPrefix predicate on the "revoke_reason" field.
func RevokeReasonHasPrefix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasPrefix(FieldRevokeReason, v))
}

// RevokeReasonHasSuffix applies the HasSuffix predicate on the "revoke_reason" field.
func RevokeReasonHasSuffix(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldHasSuffix(FieldRevokeReason, v))
}

// RevokeReasonIsNil applies the IsNil predicate on the "revoke_reason" field.
func RevokeReasonIsNil() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldIsNull(FieldRevokeReason))
}

// RevokeReasonNotNil applies the NotNil predicate on the "revoke_reason" field.
func RevokeReasonNotNil() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldNotNull(FieldRevokeReason))
}

// RevokeReasonEqualFold applies the EqualFold predicate on the "revoke_reason" field.
func RevokeReasonEqualFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldEqualFold(FieldRevokeReason, v))
}

// RevokeReasonContainsFold applies the ContainsFold predicate on the "revoke_reason" field.
func RevokeReasonContainsFold(v string) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.FieldContainsFold(FieldRevokeReason, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DesktopModelCredential) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DesktopModelCredential) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DesktopModelCredential) predicate.DesktopModelCredential {
	return predicate.DesktopModelCredential(sql.NotPredicates(p))
}
